name: Build and Push to Dockerhub
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GH_DOCKERHUB_USERNAME: ${{ env.GH_DOCKERHUB_USERNAME-Sync-env }}  # Ensure this is set if needed

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Print environment variables for debugging
      - name: Print environment variables
        run: |
          echo "GH_DOCKERHUB_USERNAME=${{ env.GH_DOCKERHUB_USERNAME-Sync-env }}"
          echo "GH_DOCKERHUB_TOKEN=***"  # HIDE actual token for security reasons
          echo "Checking if GitHub secret is accessible"
          if [ -z "${{ secrets.GH_DOCKERHUB_TOKEN }}" ]; then
            echo "DOCKERHUB_TOKEN is not set!"
            exit 1
          else
            echo "DOCKERHUB_TOKEN is set"
          fi

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.GH_DOCKERHUB_USERNAME }}
          password: ${{ secrets.GH_DOCKERHUB_TOKEN }}

      # Set up Docker Buildx for building multi-platform images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Iterate over each directory in the apps/ folder and build/push the Docker image
      - name: Build and Push Docker images
        run: |
          set -e  # Exit the script if any command fails
          for dir in ./apps/*/; do
            app_name=$(basename "$dir")
            echo "Building Docker image for $app_name"
            docker build -t ${{ env.GH_DOCKERHUB_USERNAME }}/$app_name:${{ github.sha }} -f $dir/Dockerfile $dir
            docker tag ${{ env.GH_DOCKERHUB_USERNAME }}/$app_name:${{ github.sha }} ${{ env.GH_DOCKERHUB_USERNAME }}/$app_name:latest
            
            echo "Running tests for $app_name"
            docker run --rm ${{ env.GH_DOCKERHUB_USERNAME }}/$app_name:${{ github.sha }} /bin/sh -c "./test.sh"
            
            echo "Pushing Docker image for $app_name"
            docker push ${{ env.GH_DOCKERHUB_USERNAME }}/$app_name:${{ github.sha }}
            docker push ${{ env.GH_DOCKERHUB_USERNAME }}/$app_name:latest
          done