name: Build and Push to Dockerhub
on:
  push:
    branches:
      - test

#env:
#  GH_DOCKERHUB_USERNAME: ${{ env.GH_DOCKERHUB_USERNAME }}  # Ensure this is set if needed

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3
        
    # Print and check secrets variables for debugging
      - name: Check environment variables and secrets
        run: |
          echo "Checking secrets:"
          if [ -z "${{ secrets.GH_DOCKERHUB_TOKEN }}" ]; then
            echo "GH_DOCKERHUB_TOKEN is not set!"
            exit 1
          else
            echo "GH_DOCKERHUB_TOKEN is set"
          fi

          if [ -z "${{ secrets.GH_HARBOR_PASSWORD }}" ]; then
            echo "GH_HARBOR_PASSWORD secret is not set!"
            exit 1
          else
            echo "GH_HARBOR_PASSWORD secret is set"
          fi

    # Print and check environment variables and secrets for debugging
      - name: Check environment variables and secrets
        run: |
          echo "Checking environment variables:"
          if [ -z "${{ env.GH_DOCKERHUB_USERNAME }}" ]; then
            echo "GH_DOCKERHUB_USERNAME is not set!"
            exit 1
          else
            echo "GH_DOCKERHUB_USERNAME is set: ${{ env.GH_DOCKERHUB_USERNAME }}"
          fi

          if [ -z "${{ env.GH_DOCKER_HUB_URL }}" ]; then
            echo "GH_DOCKER_HUB_URL is not set!"
            exit 1
          else
            echo "GH_DOCKER_HUB_URL is set: ${{ env.GH_DOCKER_HUB_URL }}"
          fi

          if [ -z "${{ env.GH_DOCKER_REGISTRY }}" ]; then
            echo "GH_DOCKER_REGISTRY is not set!"
            exit 1
          else
            echo "GH_DOCKER_REGISTRY is set: ${{ env.GH_DOCKER_REGISTRY }}"
          fi

          if [ -z "${{ env.GH_HARBOR_PASSWORD }}" ]; then
            echo "GH_HARBOR_PASSWORD is not set!"
            exit 1
          else
            echo "GH_HARBOR_PASSWORD is set: ***"
          fi

          if [ -z "${{ env.GH_HARBOR_REGISTRY }}" ]; then
            echo "GH_HARBOR_REGISTRY is not set!"
            exit 1
          else
            echo "GH_HARBOR_REGISTRY is set: ${{ env.GH_HARBOR_REGISTRY }}"
          fi

          if [ -z "${{ env.GH_HARBOR_URL }}" ]; then
            echo "GH_HARBOR_URL is not set!"
            exit 1
          else
            echo "GH_HARBOR_URL is set: ${{ env.GH_HARBOR_URL }}"
          fi

          if [ -z "${{ env.GH_HARBOR_USERNAME }}" ]; then
            echo "GH_HARBOR_USERNAME is not set!"
            exit 1
          else
            echo "GH_HARBOR_USERNAME is set: ${{ env.GH_HARBOR_USERNAME }}"
          fi

          if [ -z "${{ env.GH_PROJECT_NAME }}" ]; then
            echo "GH_PROJECT_NAME is not set!"
            exit 1
          else
            echo "GH_PROJECT_NAME is set: ${{ env.GH_PROJECT_NAME }}"
          fi
        
